include = "include.toml"
[tls]
ca = "example_ca"
cert = "example_cert"
key = "example_key"

[basic_auth]
user = "foo"
password = "bar"

[token_auth]
tokens = ["a", "b"]

[users.test]
id = 10001
password = "test"
keys = ["key1", "key2"]

[users.foo]
id = 10002
password = "test"

[groups.test]
id = 10001
users = ["test"]

[groups.bar]
id = 10002
users = ["foo"]
